services:
  mongodb:
    image: "mongo"
    volumes:
      - ts-docker-db:/data/db

    # environment:
    #   - MONGO_ROOT_USERNAME=ts-docker
    #   - MONGO_ROOT_PASSWORD=ts-docker


    env_file:
      - .env


  ts-backend:
    build: 
      context: ./
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    volumes:
      - ts-docker-logs:/app/logs # named volume
      - .:/app # bind mount
      - /app/node_modules #annymous volume

    env_file:
      - .env

    depends_on:
      - mongodb

  

  # ts-frontend:



volumes:
  ts-docker-db:
  ts-docker-logs:


